name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release - Windows
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 获取 pnpm store 目录
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      # 设置 pnpm 缓存
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # 安装依赖
      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm store prune

      # 安装 Tauri CLI
      - name: Install Tauri CLI
        run: pnpm add -D @tauri-apps/cli

      # 构建应用
      - name: Build the app
        run: pnpm run build && pnpm exec tauri build

      - name: Extract tag name
        id: tag
        shell: bash
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: 'Sing-Box Windows ${{ steps.tag.outputs.tag }}'
          files: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
          draft: false
          prerelease: true
          generate_release_notes: true
          body: |
            ## 🧪 预发布版本 / Pre-release Version

            **⚠️ 注意：这是一个预发布版本，主要用于测试目的。**

            ### 如何参与测试
            1. 在应用设置中启用"接收测试版本"选项
            2. 应用会自动检测并提示更新到此测试版本
            3. 如遇问题请在 [Issues](https://github.com/xinggaoya/sing-box-windows/issues) 中反馈

            ### 自动发布说明
            - ✅ 此版本已通过自动化构建和基础测试
            - 🔄 经过充分测试后会转为正式版本
            - 📝 详细更新日志请查看下方自动生成的内容

            ---

            **⚠️ Warning: This is a pre-release version for testing purposes.**

            ### How to participate in testing
            1. Enable "Accept Pre-release Versions" option in application settings
            2. The app will automatically detect and prompt to update to this test version
            3. Please report issues in [Issues](https://github.com/xinggaoya/sing-box-windows/issues)

            ### Auto-release Notes
            - ✅ This version has passed automated builds and basic tests
            - 🔄 Will be converted to stable release after sufficient testing
            - 📝 Detailed changelog is auto-generated below
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
